# Generated by Django 5.1.1 on 2024-10-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='students', to='accounts.class'),
        ),
    ]
