# Generated by Django 5.1.1 on 2024-10-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subject_remove_customuser_classes_class_subjects_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='classes',
            new_name='student_class',
        ),
    ]
